repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.2.2'
    hooks:
      # make sure the poetry config does not get committed in a broken state
      - id: poetry-check
      # make sure the lock file is up-to-date when committing changes
      # - id: poetry-lock
