---
brew:
  # recording a shell session to share with others
  - asciinema
  #  A cat(1) clone with syntax highlighting and Git integration.
  - bat
  # password management
  - bitwarden-cli
  # prettier top alternatives in C++ and Rust respectively
  # - btop
  - bottom
  # cool interactive python with colors + docs
  - bpython
  # The Matrix screensaver for the terminal
  - cmatrix
  # diff, but with colors
  - colordiff
  # prettier du/df outputs: https://github.com/muesli/duf
  - duf
  # quick system metrics, typically used as an MOTD
  - fastfetch
  # fuzzy search, helps with completion and searching
  - fzf
  # terminal user interface for git
  - gitui
  # TUI for gpg keys, for the lazy, like me
  - gpg-tui
  # search stackoverflow e.g. howdoi extend a dictionary in python
  - howdoi
  # for working w/ images and making lsimg work, is lorg
  - imagemagick
  # for parsing json via cli
  - jq
  # less: b/c you get new features if you stay up2date, & brew is up2date
  - less
  # cat images in the terminal (e.g. img2sixel imagename.png)
  - libsixel
  # ls replacement written in rust: https://github.com/Peltoche/lsd
  - lsd
  # TUI IDE is neovim 
  - neovim
  # node.js
  - node
  # file TUI: https://www.geeksforgeeks.org/ranger-a-cli-file-manager/
  - ranger
  # pretty formatting and syntax highlighting
  - rich-cli
  # python linter written in rust
  - ruff
  # get the quick, short text of how to use various commands
  - tealdeer
  # ag command: like grep or ack, but more modern, for searching file text
  - the_silver_searcher
  # blocky fonts with the options for colors
  - toilet
  # linter for YAML
  - yamllint
  # TUI browser
  - w3m
  # less complicated curl
  - wget
  # it's like jq but for yaml
  - yq
  # tmux replacement :)
  - zellij

apt:
  - bash-completion
  - build-essential
  # this is just to keep us up to date
  - git
  - curl
  - python3
  - python3-dev
  - python3-pip
  # needed for python virtual environments, especially for jedi
  - python3-venv
  # grep alternative
  - silversearcher-ag
  # this should let you use the a yubikey for auth
  - libpam-yubico
  # troubleshooting
  - sysstat
  # networking and firewall
  - iptables
  - net-tools
  # print a pretty pallete to see all colors the terminal can render
  - colortest
  # help fix locale issues
  - "locales-all"
  # for installing stuff through ssh - might not be needed with powerline anymore
  - "openssh-client"

pip3.11:
  # pip itself needs to be kept up to up2date
  - pip
  # keep ourselves up to date
  - onboardme
  # powerline: for the internal ip address prompt segment
  - netifaces
  # neovim: needed for neovim's python3 interface, I think
  - pynvim
  # this is for git pre-commits
  - pre-commit
  # powerline: (status line for tmux/BASH), this works on linux
  - "git+https://github.com/jessebot/powerline@patch-2"
  # these are powerline extensions
  - powerline-kubernetes
  - powerline-gitstatus
  # python development: linting/auto-linting
  - ruff
  - flake8
  - pyflakes
  - autoflake
  - poetry
  # this is needed to make python respect XDG Base directory specific
  - xdg_base_dirs
