---
brew:
  emoji: "🍺"
  commands:
    list: "brew list -1"
    update: "brew update --quiet"
    upgrade: "brew upgrade --quiet"
    install: "brew install "
    cleanup: "brew cleanup"
  # these are essentially just extra git repos to query for installs/updates
  taps:
    macOS:
      - "wez/wezterm"
      - "zegervdv/zathura"
  packages:
    # these are all for both macOS and Debian
    default:
      # this installs rustup which installs cargo and rust
      - rustup
      - wget
      # terminal based web browser
      - lynx
      # screen session + sharing/splitting - replaces tmux :)
      - zellij
      # recording a shell session to share with others
      - asciinema
      # main terminal based text editors
      - vim
      - neovim
      # terminal based email client
      - neomutt
      # fetch your mail locally
      - offlineimap
      # fuzzy search, helps with completion and searching
      - fzf
      # ls replacement written in rust: https://github.com/Peltoche/lsd
      - lsd
      #  A cat(1) clone with syntax highlighting and Git integration.
      - bat
      # pretty formatting and syntax highlighting
      - rich-cli
      # file TUI: https://www.geeksforgeeks.org/ranger-a-cli-file-manager/
      - ranger
      # preview videos in the terminal. commented by default because it is big
      # - ffmpegthumbnailer
      # cat images in the terminal (e.g. img2sixel imagename.png)
      - libsixel
      # for working with images and making lsimg work
      - imagemagick
      # ag command: like grep or ack, but more modern, for searching file text
      - the_silver_searcher
      # diff, but with colors
      - colordiff
      # prettier top
      - htop
      - gotop
      # quick system metrics, typically used as an MOTD
      - fastfetch
      # prettier du/df outputs: https://github.com/muesli/duf
      - duf
      # rainbow text
      - lolcat
      # blocky fonts: https://devhints.io/figlet
      - figlet
      - toilet
      # less: b/c you get new features if you stay up2date, & brew is up2date
      - less
      # steam locamotive
      - sl
      # a cow that says things
      - cowsay
      # revision control system
      - git
      # github cli
      - gh
      # gitlab cli
      - glab
      # programming languages and their package managers
      - python@3.11
      - go
      - node
      # linter for YAML
      - yamllint
      # linter for html5
      - tidy-html5
      # mardown rendering
      - pandoc
      # for parsing json via cli
      - jq
      # search stackoverflow e.g. howdoi extend a dictionary in python
      - howdoi
      # get the quick, short text of how to use various commands
      - tldr
      - tealdeer
      # generating SSL certs and random strings
      - openssl@3
      # password management
      - bitwarden-cli
      # anti virus
      - clamav
      # TUI browser
      - w3m
      # TUI for gpg keys, for the lazy, like me
      - "gpg-tui"
      # spotify daemon
      - spotifyd
      # spotify TUI
      - spotify-tui
    # macOS specific stuff. Won't work with LinuxBrew
    macOS:
      # for testing apis and downloading things
      - curl
      # current version of bash :)
      - bash
      # for setup scripts and compiling things (e.g. YouCompleteMe)
      - cmake
      # so that bash completion stuff works
      - "bash-completion@2"
      # this lets us resize windows
      - "--cask rectangle"
      # productivity search and command bar: replacing with cerebro soon
      # - "--cask alfred"
      # Default browser
      - "--cask firefox"
      # File server cloud replacement, not ready yet
      # - "--cask nextcloud"
      # Default terminal used by most macOS users, standard
      - "--cask iterm2"
      # backup terminal written in javascript :shrug:
      - "--cask hyper"
      # gives us the default gnu/linux sed we all know and love
      - "gnu-sed"
      # remap keys on macOS
      - "--cask karabiner-elements"
      # This should be docker desktop
      - "--cask docker"
      # primary media player
      - "--cask vlc"
      # youtube replacement
      - "--cask freetube"
      # firewall
      - "--cask lulu"
      # password manager
      - "--cask bitwarden"
      # VPN
      - "--cask protonvpn"
      # email
      - "--cask protonmail-bridge"
      # zathura is a document viewer
      - zathura
      - zathura-pdf-mupdf
      # libreoffice is a FOSS office suite that replaces Google Docs/Office365
      - "--cask libreoffice"
      # wezterm: Rust based terminal. I mostly use iterm2, but I use this on
      # linux and sometimes need to test on macOS for whatever reason
      - "--cask wez/wezterm/wezterm"
    devops:
      # terraform for building stuff
      - terraform
      # manage multiple versions of terraform
      - tfenv
      # cli for k8s (kubernetes)
      - kubectl
      # kubectl plugin manager
      - krew
      # terminal based dashbaord for k8s
      - k9s
      # package manager for k8s
      - helm
      # manages helm files
      - helmfile
      # cli for Bitnami sealed-secrets, encrypting secrets in yaml files for gitops
      - kubeseal
      # gitops continuous delivery for k8s configs
      - argocd
      # KinD (Kubernetes in Docker), for small k8s clusters for testing
      - kind
      # aws work stuff
      # "aws-cli"
      # aws credentials switcher
      # "--cask aws-vault"
